name: Run Smart Contract Security Analysis

on:
  workflow_dispatch: # Allows manual trigger
  push:
    paths:
      - "contracts/**.sol" # Runs when a Solidity file is added/modified
  pull_request:
    paths:
      - "contracts/**.sol"

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Solidity Compiler (solc)
      - name: Install Solidity Compiler
        run: |
          sudo apt update && sudo apt install -y solc

      # Install Slither for fast security analysis
      - name: Install Slither
        run: |
          pip install slither-analyzer

      # Run Slither and generate report
      - name: Run Slither Security Analysis
        run: |
          slither contracts/ --json slither-report.json || true

      # Install Mythril for deep symbolic execution testing
      - name: Install Mythril
        run: |
          pip install mythril

      # Run Mythril and generate report
      - name: Run Mythril Security Analysis
        run: |
          myth analyze contracts/ --execution-timeout 300 --out format=json > mythril-report.json || true

      # Upload Slither Report
      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json

      # Upload Mythril Report
      - name: Upload Mythril Report
        uses: actions/upload-artifact@v4
        with:
          name: mythril-report
          path: mythril-report.json
