name: Run Solidity Security Analysis

on:
  workflow_dispatch:
  push:
    paths:
      - "contracts/**.sol"
  pull_request:
    paths:
      - "contracts/**.sol"

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Solidity Compiler Manually
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.21/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc
          solc --version

      - name: Install Mythril
        run: |
          pip install mythril

      - name: Run Mythril Security Analysis
        run: |
          myth analyze contracts/*.sol --execution-timeout 300 --output json > mythril_report.json || true

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: mythril-report
          path: mythril_report.json
