name: Run Slither Security Analysis

on:
  workflow_dispatch: # Allows manual trigger
  push:
    paths:
      - "contracts/**.sol" # Runs when a Solidity file is added
  pull_request:
    paths:
      - "contracts/**.sol"

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Solidity Compiler
        run: |
          sudo apt update && sudo apt install -y solc

      - name: Install solc-select and Set Solidity Version
        run: |
          curl -L https://github.com/crytic/solc-select/releases/latest/download/solc-select -o solc-select
          chmod +x solc-select
          sudo mv solc-select /usr/local/bin/
          solc-select install 0.8.21  # Change this version if needed
          solc-select use 0.8.21      # Ensure this version is used

      - name: Install Slither
        run: |
          pip install slither-analyzer

      - name: Run Slither Security Analysis
        run: |
          slither contracts/ --json report.json || true

      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: report.json
