name: Solidity Security Analysis

on:
  workflow_dispatch:

jobs:
  security_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting Solidity Security Analysis"

      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Solidity Compiler
      - name: Install Solidity Compiler
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum -y
          sudo apt-get update
          sudo apt-get install -y solc
          solc --version

      # Install Mythril
      - name: Install Mythril
        run: |
          python3 -m pip install --upgrade pip
          pip3 install mythril

      - name: Run Mythril Analysis
        run: myth analyze contracts/*.sol --execution-timeout 300 --max-depth 30 --solver-timeout 1000 > mythril-report.txt || true

      - name: Upload Mythril Report
        uses: actions/upload-artifact@v4
        with:
          name: mythril-report
          path: mythril-report.txt

      # Install Slither
      - name: Install Slither
        run: |
          python3 -m pip install slither-analyzer

      - name: Run Slither Analysis
        run: slither contracts/*.sol --json slither-report.json || true

      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json

      # Install Oyente (Fixing the Requirements Issue)
      - name: Install Oyente
        run: |
          sudo apt-get install -y python3-setuptools
          git clone https://github.com/enzymefinance/oyente.git
          cd oyente
          pip3 install --upgrade pip
          pip3 install requests==2.27.1 eth-hash==0.3.2
          pip3 install -r requirements.txt || true  # Skip error if file is missing
          python3 setup.py install || true

      - name: Run Oyente Analysis
        run: cd oyente && python3 oyente.py -s ../contracts/*.sol > oyente-report.txt || true

      - name: Upload Oyente Report
        uses: actions/upload-artifact@v4
        with:
          name: oyente-report
          path: oyente-report.txt

      # Install SmartCheck
      - name: Install SmartCheck
        run: |
          git clone https://github.com/smartdec/smartcheck.git
          cd smartcheck
          pip3 install --upgrade pip
          pip3 install -r requirements.txt || true

      - name: Run SmartCheck Analysis
        run: |
          cd smartcheck
          python3 smartcheck.py -p ../contracts/ > smartcheck-report.txt || true

      - name: Upload SmartCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: smartcheck-report
          path: smartcheck-report.txt
